### ISSUE TITLE
Failed items may not get requeued if queue processing is cancelled

### ISSUE THREAD

**Issue by notbakaneko** [ppy/osu-queue-processor#14]
It seems like when a cancellation is requested, the continuation at https://github.com/ppy/osu-queue-processor/blob/master/osu.Server.QueueProcessor/QueueProcessor.cs#L132 doesn't get awaited to completion and the process can just exit without it finishing, causing items to not get requeued.

Using `osu-elastic-indexer` with a batchsize of `1000`

---
1000 items are added to the queue:
```
127.0.0.1:6381> llen osu-queue:score-index-es8
(integer) 1000
```

All items get marked as `Failed` and `Cancel()` is called on the cancellation token:

Everything is dequeued but only some of the initial items get requeued:
https://gist.github.com/notbakaneko/fa7b9c345923326da94f11db03966a96

In redis there're only 203 items in the queue instead of the expected 1000:
```
127.0.0.1:6381> llen osu-queue:score-index-es8
(integer) 203
```

This seems to be the process exiting before all the task continuations are run?

---
If a delay is added to `ProcessResults` so it doesn't return immediately (which should delay the continuations from executing), nothing gets requeued: 
```
env $(cat .env.8) schema=es8 dotnet run queue
No existing schema version set, is this intended?
Running queue with schema version es8

Using non-aliased `dev.8.solo_scores_20220719080438`.
stats: queue:1000 inflight:0 dequeued:0 processed:0 errors:0
Starting queue processing (Backlog of 1000)..
Invalid NEST response built from a successful (200) low level call on POST: /dev.8.solo_scores_20220719080438/_bulk

Shutting down..
stats: queue:0 inflight:1000 dequeued:1000 processed:0 errors:0
stats: queue:0 inflight:1000 dequeued:1000 processed:0 errors:0
stats: queue:0 inflight:1000 dequeued:1000 processed:0 errors:0
```

On redis:
```
127.0.0.1:6381> llen osu-queue:score-index-es8
(integer) 0
```

---
Everything gets added back to the queue if either the process' exit is delayed with something like `Thread.Sleep(10000)`, or `.Wait(CancellationToken.None)` is added to the task continuation in the queue processor.

**Comment by peppy** [comment]
Nice catch.

An easy fix would be to wait for `TotalInFlight` to hit zero before exiting.
