### ISSUE TITLE
Actual number of inflight items can be greater than configured MaxInFlightItems

### ISSUE THREAD

**Issue by notbakaneko** [ppy/osu-queue-processor#18]
This condition means the queue still gets popped even if total in flight items equals the configured `MaxInFlightItems`
https://github.com/ppy/osu-queue-processor/blob/master/osu.Server.QueueProcessor/QueueProcessor.cs#L100

This was confusing as I was wondering why items still kept getting popped off the queue even though it was still pending on the configured `MaxInFlightItems`

**Comment by peppy** [comment]
Just to confirm, do you mean the `>` should be a `>=` instead, or is there something more I'm missing?

**Comment by notbakaneko** [comment]
That seems to be the only thing, not sure if I'm missing anything relying on the condition being off by one 🤔
